/*
 * Understoria — Federated mutual aid timebank
 * Copyright (C) 2026 Understoria Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
/**
 * Cross-inventory coverage lock (docs/node-seizure-plan.md §5.2):
 * every kind the mirror set replicates must ALSO have a re-seed leg
 * on member devices — otherwise a "durable" kind would survive
 * mirror loss but not total node loss, and nobody would notice until
 * the drill (or the real day). The web walker's path list is copied
 * here as a LITERAL: if either inventory changes, this test fails
 * and the change must be argued against the re-seed design instead
 * of slipping in silently.
 *
 * Sanctioned exclusions — exactly two, for stated reasons:
 *  - "/claims": short-lived coordination state, not persisted
 *    client-side; already ruled loss-tolerant (the durable outcome,
 *    the exchange, has its own leg).
 *  - "/capacity-postures": node-system-signed self-attestation,
 *    regenerated by the new node; re-seeding another node's posture
 *    would be wrong, not just unnecessary.
 *
 * Re-seed-only extra: "/founder-accession" — the co-founder
 * accession record replicates via its own route on connect, not the
 * mirror loop, but MUST come back in a re-seed (it is a membership
 * trust root).
 */
import { describe, expect, it } from "vitest";
import { MIRROR_KINDS } from "./mirrorPull.js";

/** Literal copy of RESEED_KINDS' paths from
 *  apps/web/src/lib/reseed.ts — keep in the walker's order. */
const RESEED_PATHS = [
  "/redemptions",
  "/founder-accession",
  "/invite-revocations",
  "/events",
  "/event-cancellations",
  "/project-states",
  "/task-states",
  "/event-shifts",
  "/event-rsvps",
  "/seed-vault-pledges",
  "/member-removals",
  "/member-reinstatements",
  "/proposals",
  "/votes",
  "/proposal-closures",
  "/shift-signups",
  "/posts",
  "/exchanges",
  "/vouches",
  "/task-comments",
  "/coorg-invitations",
  "/coorg-invitation-responses",
  "/coorg-invitation-revocations",
] as const;

const SANCTIONED_MIRROR_ONLY = new Set(["/claims", "/capacity-postures"]);

describe("reseed coverage of the mirror inventory", () => {
  it("every mirrored kind outside the two sanctioned exclusions has a re-seed leg", () => {
    const reseed = new Set<string>(RESEED_PATHS);
    const uncovered = MIRROR_KINDS.map((k) => k.path).filter(
      (p) => !SANCTIONED_MIRROR_ONLY.has(p) && !reseed.has(p),
    );
    expect(uncovered).toEqual([]);
  });

  it("the sanctioned exclusions are real mirror kinds (no stale allowlist)", () => {
    const mirror = new Set(MIRROR_KINDS.map((k) => k.path));
    for (const p of SANCTIONED_MIRROR_ONLY) {
      expect(mirror.has(p), `${p} no longer mirrored — prune the allowlist`).toBe(
        true,
      );
    }
  });

  it("the re-seed-only extra is exactly /founder-accession", () => {
    const mirror = new Set(MIRROR_KINDS.map((k) => k.path));
    const extras = RESEED_PATHS.filter((p) => !mirror.has(p));
    expect(extras).toEqual(["/founder-accession"]);
  });
});
