/*
 * Understoria — Federated mutual aid timebank
 * Copyright (C) 2026 Understoria Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program. If not, see
 * <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
import { MINIMUM_VOUCHES_FOR_TRUST } from "@/lib/vouch";

// "Grow another root" — the pure half of the guided add-a-node flow
// (docs/add-a-node.md, operator-guide §6 mirror runbook). Everything
// here is unit-testable with no DOM, no Dexie, no network: token and
// node-id generation, the two ready-to-paste env blocks, and the
// post-setup verification probes (which take an injectable fetch).

/**
 * The vouch threshold that opens the guided wizard. Deliberately a
 * re-export of the community's existing "trusted" bar
 * (`MINIMUM_VOUCHES_FOR_TRUST`): a mirror operator gains the read
 * powers named in docs/operator-powers.md, so recruiting into that
 * role asks the same trust question the rest of the app already asks
 * about a member — no new number to govern. Honest note: this gate is
 * UI friction, not a security boundary. The docs the wizard is built
 * from remain public (docs/add-a-node.md, operator-guide §6), and the
 * real controls stay where they were: NODE_FOUNDER_KEYS agreement,
 * READ_AUTH, and the current operator's consent to pair.
 */
export const MIN_VOUCHES_TO_GROW = MINIMUM_VOUCHES_FOR_TRUST;

/**
 * A fresh shared read token for the mirror pair: 32 random bytes,
 * base64url without padding (43 chars — comfortably over the ≥16-char
 * floor `PEER_READ_TOKENS` / `MIRROR_READ_TOKENS` document). Generated
 * on the member's device and meant to travel only by copy/QR between
 * the two operators, never over the network.
 */
export function generateMirrorToken(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  // Canonical base64 over the raw bytes, then the url-safe alphabet
  // swap and padding strip.
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

const BASE36 = "0123456789abcdefghijklmnopqrstuvwxyz";

/**
 * Suggest a NODE_ID for the new mirror: the origin's id plus a short
 * random suffix. The suffix (4 random base36 chars, ~1.7M values)
 * keeps two communities that both grew a "<origin>_root2" from ever
 * colliding — node ids ride on every federated record, so a duplicate
 * would be genuinely confusing.
 */
export function suggestNodeId(originNodeId: string): string {
  const bytes = new Uint8Array(4);
  crypto.getRandomValues(bytes);
  let suffix = "";
  for (const b of bytes) suffix += BASE36[b % 36];
  return `${originNodeId}_${suffix}`;
}

function stripTrailingSlash(url: string): string {
  return url.trim().replace(/\/+$/, "");
}

/**
 * The ready-to-paste `.env` block for the NEW server. Faithful to the
 * operator-guide §6 mirror runbook: same trust settings as the origin,
 * its own DATABASE_KEY, MIRROR_NODE_URLS pointed at the origin, the
 * shared read token only when the community's read gate is on. Lines
 * the wizard cannot know (`NODE_FOUNDER_KEYS`, `REMOVAL_QUORUM`, the
 * freshly generated `DATABASE_KEY`) are explicit placeholders — they
 * must come from the current operator or a local command, never from
 * this app.
 */
export function buildMirrorEnv(input: {
  originUrl: string;
  pwaOrigin: string;
  readAuthOn: boolean;
  token: string;
  nodeId: string;
}): string {
  const originUrl = stripTrailingSlash(input.originUrl);
  const pwaOrigin = stripTrailingSlash(input.pwaOrigin);
  const lines: string[] = [
    '# .env for the NEW server — generated by "Grow another root".',
    "# Full reference: operator-guide §6; walkthrough: docs/add-a-node.md.",
    "",
    "# A stable name for this node — it rides on every record it federates.",
    `NODE_ID=${input.nodeId}`,
    "",
    "# Encrypt the database at rest BEFORE any data touches the disk.",
    "# Generate a key with:  openssl rand -base64 32",
    "# (keep a copy of the key somewhere that is NOT next to the backups)",
    "DATABASE_KEY=<paste the key you generated>",
    "",
    "# The gotcha: the mirror must allow the community's PWA origin,",
    "# or members' apps can't fail over to it.",
    `CORS_ORIGIN=${pwaOrigin}`,
    "",
    "# Replicate every record from the community's current server.",
    `MIRROR_NODE_URLS=${originUrl}`,
  ];
  if (input.readAuthOn) {
    lines.push(
      "",
      "# The community's read gate is ON — this server must be exactly as",
      "# closed to strangers as the current one.",
      "READ_AUTH=on",
      `MIRROR_READ_TOKENS={"${originUrl}":"${input.token}"}`,
    );
  } else {
    lines.push(
      "",
      "# Matches the current server's read gate. If the community ever",
      "# flips READ_AUTH on, it must flip on every server at once.",
      "READ_AUTH=off",
    );
  }
  lines.push(
    "",
    "# Must match the current server EXACTLY — same community, same",
    "# trust roots. Copy it, don't retype it.",
    "NODE_FOUNDER_KEYS=<ask your current operator — must match exactly>",
    "",
    "# Must match the current server's rule too.",
    "REMOVAL_QUORUM=<match the origin>",
    "",
  );
  return lines.join("\n");
}

/**
 * The short block the CURRENT operator adds to pair the servers and
 * announce the new one to members' apps (operator-guide §6 runbook
 * steps 2–4). `MIRROR_NODE_URLS` / `MIRROR_ANNOUNCE_URLS` are
 * comma-separated lists — the comment says "append", since the origin
 * may already mirror other nodes.
 */
export function buildOriginHandover(input: {
  newNodeUrl: string;
  token: string;
  readAuthOn: boolean;
}): string {
  const newNodeUrl = stripTrailingSlash(input.newNodeUrl);
  const lines: string[] = [
    "# For the CURRENT server's .env — append the new address to each",
    "# list (comma-separated if a value is already there):",
    `MIRROR_NODE_URLS=${newNodeUrl}`,
    `MIRROR_ANNOUNCE_URLS=${newNodeUrl}`,
  ];
  if (input.readAuthOn) {
    lines.push(
      "# And add this entry to the MIRROR_READ_TOKENS map:",
      `MIRROR_READ_TOKENS={"${newNodeUrl}":"${input.token}"}`,
    );
  }
  lines.push("# Then apply:  docker compose up -d");
  return lines.join("\n");
}

/**
 * The verification checks the wizard's last step runs.
 *
 * `readAuthMatch` is declared for completeness but NEVER emitted by
 * `probeNewRoot`: `GET /config` deliberately does not publish the
 * node's READ_AUTH state (see `PublicConfigResponse` in
 * apps/server/src/routes/config.ts — operational details stay off the
 * public surface), so the app cannot verify the gate matches without
 * faking it. The env blocks and the docs carry that responsibility
 * instead.
 */
export type RootCheckId =
  | "reachable"
  | "config"
  | "distinctNodeId"
  | "readAuthMatch"
  | "announced";

export interface RootCheckResult {
  id: RootCheckId;
  /** `true` = verified, `false` = checked and failing, `null` = could
   *  not determine (e.g. a /config that doesn't publish the field). */
  ok: boolean | null;
  detail?: string;
}

const PROBE_TIMEOUT_MS = 4_000;

function probeInit(): RequestInit {
  return {
    signal: AbortSignal.timeout(PROBE_TIMEOUT_MS),
    credentials: "omit",
    mode: "cors",
  };
}

/**
 * Probe a freshly set-up mirror. Never throws; a network failure marks
 * the affected check `ok: false` (or `ok: null` where failure means
 * "couldn't ask", see below) and every check is always present in the
 * result, in a stable order.
 *
 * Checks:
 * - `reachable`  — `GET <url>/health` answers OK.
 * - `config`     — `GET <url>/config` answers OK with a JSON object.
 * - `distinctNodeId` — the new node's published `nodeId` differs from
 *   the origin's. `null` when either side doesn't publish one
 *   (`/config.nodeId` only appears alongside a system key).
 * - `announced`  — the ORIGIN's `/config.mirrors` lists the new URL
 *   (trailing slashes normalized). Semantic when the origin itself
 *   can't be reached or errors: `ok: null` — we could not ask, and
 *   refusing to answer is more honest than claiming the mirror isn't
 *   announced. An origin that answers without a `mirrors` field IS a
 *   definite `false` (nothing is announced).
 */
export async function probeNewRoot(input: {
  url: string;
  originUrl: string;
  originNodeId: string | null;
  fetchImpl?: typeof fetch;
}): Promise<RootCheckResult[]> {
  const fetchImpl = input.fetchImpl ?? globalThis.fetch;
  const url = stripTrailingSlash(input.url);
  const originUrl = stripTrailingSlash(input.originUrl);
  const results: RootCheckResult[] = [];

  // reachable — /health is an open route (exempt from READ_AUTH).
  let reachable = false;
  try {
    const res = await fetchImpl(`${url}/health`, probeInit());
    reachable = res.ok;
  } catch {
    reachable = false;
  }
  results.push({ id: "reachable", ok: reachable });

  // config — capture the published nodeId if the response carries one.
  let configOk = false;
  let newNodeId: string | null = null;
  try {
    const res = await fetchImpl(`${url}/config`, probeInit());
    if (res.ok) {
      const body = (await res.json()) as { nodeId?: unknown } | null;
      if (body && typeof body === "object") {
        configOk = true;
        if (typeof body.nodeId === "string" && body.nodeId.length > 0) {
          newNodeId = body.nodeId;
        }
      }
    }
  } catch {
    configOk = false;
  }
  results.push({ id: "config", ok: configOk });

  // distinctNodeId — both ids must be known to say anything.
  if (newNodeId !== null && input.originNodeId !== null) {
    results.push({
      id: "distinctNodeId",
      ok: newNodeId !== input.originNodeId,
      detail: newNodeId,
    });
  } else {
    results.push({ id: "distinctNodeId", ok: null });
  }

  // announced — ask the ORIGIN whether it announces the new URL.
  let announced: boolean | null = null;
  try {
    const res = await fetchImpl(`${originUrl}/config`, probeInit());
    if (res.ok) {
      const body = (await res.json()) as { mirrors?: unknown } | null;
      const mirrors =
        body && typeof body === "object" && Array.isArray(body.mirrors)
          ? body.mirrors
          : [];
      announced = mirrors.some(
        (m) => typeof m === "string" && stripTrailingSlash(m) === url,
      );
    }
  } catch {
    announced = null;
  }
  results.push({ id: "announced", ok: announced });

  return results;
}
